SIM ?= icarus
TOPLEVEL_LANG ?= verilog
UNIT ?= instruction_memory

SRC_DIR := $(abspath ../src)
VERILOG_SOURCES := $(SRC_DIR)/$(UNIT).v
SIM_BUILD := sim_build/units/$(UNIT)
TOPLEVEL := $(UNIT)
COCOTB_TEST_MODULES := test_units
COMPILE_ARGS += -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim
